### ISSUE TITLE
ssh key hakkinda

### ISSUE THREAD

**Issue by ZulfikarGokyar** [devopsyolu/bootcamp#11]
selamlar hocam,
bir aws hesabi icin sadece bir cift  mi private=public key olusturulabilir ?
benim public key'imi ogrenen birisi aws'deki islem gecmisimi ogrenebilir mi?
konuyla ilgili kaynak onerisi alabilirim.
tesekkurler

**Comment by devopsyolu** [comment]
merhaba zulfikat
ssh keyler pair dir yani cifttir ve private ve public olarak olusur. aws hesabi icin key farkli birsey, ssh key olusturmak farkli birsey.
ssh baglanti yaptigin yerlerde private keyini ogrenen biri oraya ssh kullanarak baglanabilir.

aws de access key ve secret key var. bunlar farkli seyler.
aws de de secret keyini ogrenen biri access key ile beraber awsde istedigini yapabilir.

ozet:
bir aws hesabi icin sadece bir cift mi private=public key olusturulabilir ?
soru yanlis.
benim public key'imi ogrenen birisi aws'deki islem gecmisimi ogrenebilir mi?
soru yanlis.

konuyla ilgili kaynak onerisi alabilirim.
google: sshkey nedir? aws access, secret key nedir?

aws kismini gelecek hafta gorecegiz.

**Comment by ZulfikarGokyar** [comment]
Teşekkürler Kemal hocam, cehalet başa bela; doğru şeyi yanlış ve alakasız
bir şekilde de sorabiliyor insan:)

28 Ara 2024 Cmt 19:06 tarihinde Devops Yolu ***@***.***> şunu
yazdı:

**Comment by kemalgoekhan** [comment]
Boyle ogreniliyor zaten sorun yok
